#!/usr/bin/ruby
# Usage: change list
# Summary: List all the changes (local & on the remote).
# Help: Displays a list of all the changes avalible by looking at all the local
# and remote branches prefixed with "change/".

require File.join(File.dirname(__FILE__), "../share/change/helpers")

begin

  all = `git branch -a --no-color`.lines.select do |branch|
    branch =~ %r{^[\*\s]*(remotes/origin/)?change/.*?\s*$}
  end.collect do |branch|
    branch[%r{^[\*\s]*(remotes/origin/)?change/(.*?)\s*$}, 2]
  end.uniq.sort

  puts all

rescue Exception => error

  handle_error(error)

end
