#!/usr/bin/ruby
# Usage: change ds [-f] [--skip-fetch] [--return-branch]
# Summary: Delete the staging branch.
# Help: Delete the staging branch locally & on the remote.
#
# Sometimes the staging branch will end up with commits that you don't want
# staged (abandonded features for example). When this happens you can delete the
# staging branch ready for a new one to be created.
#
# Most of the time you'll need to use the -f option to force the branch to be
# deleted.

require File.join(File.dirname(__FILE__), "../share/change/helpers")

# options
force = ARGV.delete("-f")
skip_fetch = ARGV.delete("--skip-fetch")
return_branch = extract_string_option(ARGV, "--return-branch")
# observations
initial_branch = current_branch

begin

  # Preflight.

  unless head_is_clean
    raise DirtyHeadError.new
  end

  # Fetch.

  unless skip_fetch
    run_or_raise("git fetch -p")
  end

  # Checkout and pull the STAGING branch.

  unless on_branch("staging")
    run_or_raise("git checkout staging")
  end

  if has_branch("remotes/origin/staging")
    run_or_raise("git merge origin/staging")
  end

  # Checkout & pull the MASTER branch.

  run_or_raise("git checkout master")
  run_or_raise("git merge origin/master")

  # Delete the STAGING branch.

  if has_branch("remotes/origin/staging")
    run_or_raise("git push --delete origin staging")
  end

  if force
    run_or_raise("git branch -D staging")
  else
    run_or_raise("git branch -d staging")
  end

  # Finish.

  if return_branch
    run_or_raise("git checkout #{return_branch}")
  elsif has_branch(initial_branch)
    run_or_raise("git checkout #{initial_branch}")
  end

  put_success("The staging branch has been deleted.")

rescue Exception => error

  handle_error(error)

end
