#!/usr/bin/ruby
# Usage: change checkout <change> [--fetch]
# Summary: Checkout a change branch.
# Help: Checkout a change branch.

require File.join(File.dirname(__FILE__), "../share/change/helpers")

# options
complete = ARGV.delete("--complete")
fetch = ARGV.delete("--fetch")
# arguments
name = ARGV.shift

# Provide change completions
if complete
  puts `change list`
  exit
end

begin

  # Preflight.

  if name.to_s.strip.empty?
    raise ArgumentError.new("You must pass the name of the change to checkout:\n  change checkout <name>")
  else
    change_branch = "change/#{name}"
  end

  unless head_is_clean
    raise DirtyHeadError.new
  end

  # Fetch.

  if fetch
    run_or_raise("git fetch -p")
  end

  # Checkout the branch.

  run_or_raise("git checkout #{change_branch}")

  if has_branch("remotes/origin/#{change_branch}")
    run_or_raise("git merge origin/#{change_branch}")
  end

  put_success("Done.")

rescue Exception => error

  handle_error(error)

end
